import type { Metadata } from "next";
import { ClientProvider } from "@/core/providers/ClientProvider";

export const metadata: Metadata = {
  title: "Next lesson",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ClientProvider>
          {children}
        </ClientProvider>
      </body>
    </html>
  );
}
